# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180613_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-id'], 'verbose_name': '\u56fe\u4e66', 'verbose_name_plural': '\u56fe\u4e66'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5bfc\u822a\u5206\u7c7b'),
        ),
    ]
