# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180619_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='html',
            field=models.TextField(default='', help_text='\u6b63\u6587\u53ef\u4ee5\u4f7f\u7528markdown', verbose_name='html\u6e32\u67d3\u540e\u7684\u9875\u9762'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='\u4f7f\u7528markdown'),
        ),
    ]
